version: 2
updates:
  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: daily
      time: "13:00"
    groups:
      python-packages:
        patterns:
          - "*"
    assignees:
      - "kermany"