name: Cut release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Version for the tagged release"
        required: true
      next-version:
        description: "Next version"
        required: true
  pull_request:


jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '8'

        - name: git config
          run: |
            git config --global user.name "glow-release[bot]"
            git config --global user.email "glow-release-bot@noreply.projectglow.io"

        - name: Cut release with SBT
          # run: "sbt 'set releaseType := \"cutRelease\"' 'release release-version ${{ inputs.release-version }} next-version ${{ inputs.next-version }}'"
          run: "sbt 'set releaseType := \"cutRelease\"' 'release release-version 2.0.1-test next-version 2.0.0-SNAPSHOT'"

        - name: Push main and release tag
          # run: |
          #   git push origin main
          #   git push origin v${{ inputs.release-version }}
          run: 
            git push origin main
            git push origin v2.0.1-test