name: Cut release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Version for the tagged release"
        required: true
      next-version:
        description: "Next version"
        required: true


jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '8'

        - name: Cut release with SBT
          run: "sbt 'set releaseType := \"cutRelease\"' 'release release-version ${{ inputs.release-version }} next-version ${{ inputs.next-version }}'"

        - name: Push main and release tag
          run: |
            git push origin main
            git push origin v${{ inputs.release-version }}