name: Deploy to staging

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    defaults:
        run: 
            shell: bash -el {0}
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '8'
        
        - name: Install Conda
          uses: conda-incubator/setup-miniconda@v3
          with:
            conda-solver: libmamba
            activate-environment: glow
            environment-file: python/environment.yml

        - Scala